# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RbMoniter.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RbMoniter(object):
    def setupUi(self, RbMoniter):
        RbMoniter.setObjectName("RbMoniter")
        RbMoniter.resize(1293, 1058)
        self.centralwidget = QtWidgets.QWidget(RbMoniter)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_display = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_display.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_display.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_display.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_display.setObjectName("tabWidget_display")
        self.tab_fullRBLockMoniter = QtWidgets.QWidget()
        self.tab_fullRBLockMoniter.setObjectName("tab_fullRBLockMoniter")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_fullRBLockMoniter)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pw_temp = PlotWidget(self.tab_fullRBLockMoniter)
        self.pw_temp.setObjectName("pw_temp")
        self.gridLayout.addWidget(self.pw_temp, 3, 0, 1, 2)
        self.pw_velocitytimeseries = PlotWidget(self.tab_fullRBLockMoniter)
        self.pw_velocitytimeseries.setObjectName("pw_velocitytimeseries")
        self.gridLayout.addWidget(self.pw_velocitytimeseries, 2, 0, 1, 2)
        self.pw_etalondata = PlotWidget(self.tab_fullRBLockMoniter)
        self.pw_etalondata.setObjectName("pw_etalondata")
        self.gridLayout.addWidget(self.pw_etalondata, 0, 0, 1, 1)
        self.glw_rawtimeseries = GraphicsLayoutWidget(self.tab_fullRBLockMoniter)
        self.glw_rawtimeseries.setObjectName("glw_rawtimeseries")
        self.gridLayout.addWidget(self.glw_rawtimeseries, 1, 0, 1, 2)
        self.pw_rbdata = PlotWidget(self.tab_fullRBLockMoniter)
        self.pw_rbdata.setObjectName("pw_rbdata")
        self.gridLayout.addWidget(self.pw_rbdata, 0, 1, 1, 1)
        self.tabWidget_display.addTab(self.tab_fullRBLockMoniter, "")
        self.tab_RBLockDiagnostic = QtWidgets.QWidget()
        self.tab_RBLockDiagnostic.setObjectName("tab_RBLockDiagnostic")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_RBLockDiagnostic)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pw_DiagnosticEtalonPlot = PlotWidget(self.tab_RBLockDiagnostic)
        self.pw_DiagnosticEtalonPlot.setObjectName("pw_DiagnosticEtalonPlot")
        self.gridLayout_2.addWidget(self.pw_DiagnosticEtalonPlot, 0, 0, 1, 1)
        self.pw_DiagnosticRbPlot = PlotWidget(self.tab_RBLockDiagnostic)
        self.pw_DiagnosticRbPlot.setObjectName("pw_DiagnosticRbPlot")
        self.gridLayout_2.addWidget(self.pw_DiagnosticRbPlot, 1, 0, 1, 1)
        self.tabWidget_display.addTab(self.tab_RBLockDiagnostic, "")
        self.tab_SpecCamera = QtWidgets.QWidget()
        self.tab_SpecCamera.setObjectName("tab_SpecCamera")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_SpecCamera)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_fullCCDImage = QtWidgets.QLabel(self.tab_SpecCamera)
        self.label_fullCCDImage.setObjectName("label_fullCCDImage")
        self.gridLayout_10.addWidget(self.label_fullCCDImage, 0, 0, 1, 1)
        self.label_MaxZoom = QtWidgets.QLabel(self.tab_SpecCamera)
        self.label_MaxZoom.setObjectName("label_MaxZoom")
        self.gridLayout_10.addWidget(self.label_MaxZoom, 0, 1, 1, 1)
        self.pw_maxValueZoom = PlotWidget(self.tab_SpecCamera)
        self.pw_maxValueZoom.setMaximumSize(QtCore.QSize(280, 280))
        self.pw_maxValueZoom.setObjectName("pw_maxValueZoom")
        self.gridLayout_10.addWidget(self.pw_maxValueZoom, 1, 1, 1, 1)
        self.label_mouseZoom = QtWidgets.QLabel(self.tab_SpecCamera)
        self.label_mouseZoom.setObjectName("label_mouseZoom")
        self.gridLayout_10.addWidget(self.label_mouseZoom, 2, 1, 1, 1)
        self.pw_mouseValueZoom = PlotWidget(self.tab_SpecCamera)
        self.pw_mouseValueZoom.setMaximumSize(QtCore.QSize(280, 280))
        self.pw_mouseValueZoom.setObjectName("pw_mouseValueZoom")
        self.gridLayout_10.addWidget(self.pw_mouseValueZoom, 3, 1, 1, 1)
        self.pw_FullCCDImage = PlotWidget(self.tab_SpecCamera)
        self.pw_FullCCDImage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pw_FullCCDImage.setBaseSize(QtCore.QSize(600, 600))
        self.pw_FullCCDImage.setObjectName("pw_FullCCDImage")
        self.gridLayout_10.addWidget(self.pw_FullCCDImage, 1, 0, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 4, 1, 1, 1)
        self.tabWidget_display.addTab(self.tab_SpecCamera, "")
        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_log)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(self.tab_log)
        self.plainTextEdit_log.setAutoFillBackground(False)
        self.plainTextEdit_log.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plainTextEdit_log.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plainTextEdit_log.setDocumentTitle("")
        self.plainTextEdit_log.setReadOnly(True)
        self.plainTextEdit_log.setBackgroundVisible(False)
        self.plainTextEdit_log.setCenterOnScroll(False)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.gridLayout_12.addWidget(self.plainTextEdit_log, 0, 0, 1, 1)
        self.tabWidget_display.addTab(self.tab_log, "")
        self.horizontalLayout.addWidget(self.tabWidget_display)
        self.tabWidget_controls = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_controls.setMinimumSize(QtCore.QSize(0, 250))
        self.tabWidget_controls.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.tabWidget_controls.setFont(font)
        self.tabWidget_controls.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_controls.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_controls.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget_controls.setTabBarAutoHide(False)
        self.tabWidget_controls.setObjectName("tabWidget_controls")
        self.LiveTab = QtWidgets.QWidget()
        self.LiveTab.setObjectName("LiveTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.LiveTab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RbLockDataAqusitionControls = QtWidgets.QGroupBox(self.LiveTab)
        self.RbLockDataAqusitionControls.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.RbLockDataAqusitionControls.setObjectName("RbLockDataAqusitionControls")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.RbLockDataAqusitionControls)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_TempSetPoint = QtWidgets.QLabel(self.RbLockDataAqusitionControls)
        self.label_TempSetPoint.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_TempSetPoint.setObjectName("label_TempSetPoint")
        self.gridLayout_3.addWidget(self.label_TempSetPoint, 8, 0, 1, 1)
        self.pushButton_clearData = QtWidgets.QPushButton(self.RbLockDataAqusitionControls)
        self.pushButton_clearData.setObjectName("pushButton_clearData")
        self.gridLayout_3.addWidget(self.pushButton_clearData, 1, 1, 1, 1)
        self.label_RbSmoothWindow = QtWidgets.QLabel(self.RbLockDataAqusitionControls)
        self.label_RbSmoothWindow.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_RbSmoothWindow.setObjectName("label_RbSmoothWindow")
        self.gridLayout_3.addWidget(self.label_RbSmoothWindow, 5, 0, 1, 1)
        self.checkBox_etalonsmoothing = QtWidgets.QCheckBox(self.RbLockDataAqusitionControls)
        self.checkBox_etalonsmoothing.setObjectName("checkBox_etalonsmoothing")
        self.gridLayout_3.addWidget(self.checkBox_etalonsmoothing, 3, 0, 1, 1)
        self.spinBox_updaterate = QtWidgets.QSpinBox(self.RbLockDataAqusitionControls)
        self.spinBox_updaterate.setMinimum(5)
        self.spinBox_updaterate.setObjectName("spinBox_updaterate")
        self.gridLayout_3.addWidget(self.spinBox_updaterate, 7, 1, 1, 1)
        self.doubleSpinBox_tempsetpoint = QtWidgets.QDoubleSpinBox(self.RbLockDataAqusitionControls)
        self.doubleSpinBox_tempsetpoint.setDecimals(4)
        self.doubleSpinBox_tempsetpoint.setMinimum(-99.0)
        self.doubleSpinBox_tempsetpoint.setMaximum(99.0)
        self.doubleSpinBox_tempsetpoint.setSingleStep(0.0001)
        self.doubleSpinBox_tempsetpoint.setProperty("value", 0.0)
        self.doubleSpinBox_tempsetpoint.setObjectName("doubleSpinBox_tempsetpoint")
        self.gridLayout_3.addWidget(self.doubleSpinBox_tempsetpoint, 8, 1, 1, 1)
        self.spinBox_smoothingWindow = QtWidgets.QSpinBox(self.RbLockDataAqusitionControls)
        self.spinBox_smoothingWindow.setSuffix("")
        self.spinBox_smoothingWindow.setMinimum(5)
        self.spinBox_smoothingWindow.setMaximum(2001)
        self.spinBox_smoothingWindow.setSingleStep(2)
        self.spinBox_smoothingWindow.setProperty("value", 51)
        self.spinBox_smoothingWindow.setObjectName("spinBox_smoothingWindow")
        self.gridLayout_3.addWidget(self.spinBox_smoothingWindow, 5, 1, 1, 1)
        self.label_DisplayUpdateRate = QtWidgets.QLabel(self.RbLockDataAqusitionControls)
        self.label_DisplayUpdateRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_DisplayUpdateRate.setObjectName("label_DisplayUpdateRate")
        self.gridLayout_3.addWidget(self.label_DisplayUpdateRate, 7, 0, 1, 1)
        self.pushButton_savedata = QtWidgets.QPushButton(self.RbLockDataAqusitionControls)
        self.pushButton_savedata.setObjectName("pushButton_savedata")
        self.gridLayout_3.addWidget(self.pushButton_savedata, 1, 0, 1, 1)
        self.label_EtalonBinSize = QtWidgets.QLabel(self.RbLockDataAqusitionControls)
        self.label_EtalonBinSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_EtalonBinSize.setObjectName("label_EtalonBinSize")
        self.gridLayout_3.addWidget(self.label_EtalonBinSize, 6, 0, 1, 1)
        self.label_plotwindowsize = QtWidgets.QLabel(self.RbLockDataAqusitionControls)
        self.label_plotwindowsize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_plotwindowsize.setObjectName("label_plotwindowsize")
        self.gridLayout_3.addWidget(self.label_plotwindowsize, 9, 0, 1, 1)
        self.checkBox_fitting = QtWidgets.QCheckBox(self.RbLockDataAqusitionControls)
        self.checkBox_fitting.setEnabled(True)
        self.checkBox_fitting.setChecked(False)
        self.checkBox_fitting.setObjectName("checkBox_fitting")
        self.gridLayout_3.addWidget(self.checkBox_fitting, 3, 1, 1, 1)
        self.startbutton = QtWidgets.QPushButton(self.RbLockDataAqusitionControls)
        self.startbutton.setDefault(False)
        self.startbutton.setFlat(False)
        self.startbutton.setObjectName("startbutton")
        self.gridLayout_3.addWidget(self.startbutton, 0, 0, 1, 1)
        self.doubleSpinBox_etalonbinsize = QtWidgets.QDoubleSpinBox(self.RbLockDataAqusitionControls)
        self.doubleSpinBox_etalonbinsize.setReadOnly(False)
        self.doubleSpinBox_etalonbinsize.setPrefix("")
        self.doubleSpinBox_etalonbinsize.setMinimum(0.1)
        self.doubleSpinBox_etalonbinsize.setMaximum(1000.0)
        self.doubleSpinBox_etalonbinsize.setProperty("value", 1.0)
        self.doubleSpinBox_etalonbinsize.setObjectName("doubleSpinBox_etalonbinsize")
        self.gridLayout_3.addWidget(self.doubleSpinBox_etalonbinsize, 6, 1, 1, 1)
        self.stopbutton = QtWidgets.QPushButton(self.RbLockDataAqusitionControls)
        self.stopbutton.setEnabled(False)
        self.stopbutton.setObjectName("stopbutton")
        self.gridLayout_3.addWidget(self.stopbutton, 0, 1, 1, 1)
        self.spinBox_plotwindowsize = QtWidgets.QSpinBox(self.RbLockDataAqusitionControls)
        self.spinBox_plotwindowsize.setMinimum(500)
        self.spinBox_plotwindowsize.setMaximum(20000)
        self.spinBox_plotwindowsize.setSingleStep(500)
        self.spinBox_plotwindowsize.setProperty("value", 2000)
        self.spinBox_plotwindowsize.setObjectName("spinBox_plotwindowsize")
        self.gridLayout_3.addWidget(self.spinBox_plotwindowsize, 9, 1, 1, 1)
        self.verticalLayout.addWidget(self.RbLockDataAqusitionControls, 0, QtCore.Qt.AlignTop)
        self.MeasurmentsDisplay = QtWidgets.QGroupBox(self.LiveTab)
        self.MeasurmentsDisplay.setObjectName("MeasurmentsDisplay")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.MeasurmentsDisplay)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_dateRate = QtWidgets.QLabel(self.MeasurmentsDisplay)
        self.label_dateRate.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_dateRate.setFont(font)
        self.label_dateRate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_dateRate.setAutoFillBackground(False)
        self.label_dateRate.setObjectName("label_dateRate")
        self.gridLayout_4.addWidget(self.label_dateRate, 0, 0, 1, 1)
        self.label_StdEtalon = QtWidgets.QLabel(self.MeasurmentsDisplay)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_StdEtalon.setFont(font)
        self.label_StdEtalon.setObjectName("label_StdEtalon")
        self.gridLayout_4.addWidget(self.label_StdEtalon, 2, 2, 1, 1)
        self.lcdNumber_fitrate = QtWidgets.QLCDNumber(self.MeasurmentsDisplay)
        self.lcdNumber_fitrate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_fitrate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber_fitrate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_fitrate.setObjectName("lcdNumber_fitrate")
        self.gridLayout_4.addWidget(self.lcdNumber_fitrate, 1, 1, 1, 1)
        self.lcdNumber_etalonStd = QtWidgets.QLCDNumber(self.MeasurmentsDisplay)
        self.lcdNumber_etalonStd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_etalonStd.setSmallDecimalPoint(False)
        self.lcdNumber_etalonStd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_etalonStd.setObjectName("lcdNumber_etalonStd")
        self.gridLayout_4.addWidget(self.lcdNumber_etalonStd, 2, 3, 1, 1)
        self.lcdNumber_rbStd = QtWidgets.QLCDNumber(self.MeasurmentsDisplay)
        self.lcdNumber_rbStd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_rbStd.setSmallDecimalPoint(False)
        self.lcdNumber_rbStd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_rbStd.setProperty("value", 0.0)
        self.lcdNumber_rbStd.setObjectName("lcdNumber_rbStd")
        self.gridLayout_4.addWidget(self.lcdNumber_rbStd, 2, 1, 1, 1)
        self.label_TriggerCount = QtWidgets.QLabel(self.MeasurmentsDisplay)
        self.label_TriggerCount.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_TriggerCount.setFont(font)
        self.label_TriggerCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_TriggerCount.setAutoFillBackground(False)
        self.label_TriggerCount.setObjectName("label_TriggerCount")
        self.gridLayout_4.addWidget(self.label_TriggerCount, 0, 2, 1, 1)
        self.label_StdRb = QtWidgets.QLabel(self.MeasurmentsDisplay)
        self.label_StdRb.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_StdRb.setFont(font)
        self.label_StdRb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_StdRb.setAutoFillBackground(False)
        self.label_StdRb.setObjectName("label_StdRb")
        self.gridLayout_4.addWidget(self.label_StdRb, 2, 0, 1, 1)
        self.lcdNumber_dateRate = QtWidgets.QLCDNumber(self.MeasurmentsDisplay)
        self.lcdNumber_dateRate.setMaximumSize(QtCore.QSize(16777215, 16777212))
        self.lcdNumber_dateRate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_dateRate.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdNumber_dateRate.setSmallDecimalPoint(False)
        self.lcdNumber_dateRate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_dateRate.setObjectName("lcdNumber_dateRate")
        self.gridLayout_4.addWidget(self.lcdNumber_dateRate, 0, 1, 1, 1)
        self.label_Fitrate = QtWidgets.QLabel(self.MeasurmentsDisplay)
        self.label_Fitrate.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Fitrate.setFont(font)
        self.label_Fitrate.setObjectName("label_Fitrate")
        self.gridLayout_4.addWidget(self.label_Fitrate, 1, 0, 1, 1)
        self.lcdNumber_triggerCount = QtWidgets.QLCDNumber(self.MeasurmentsDisplay)
        self.lcdNumber_triggerCount.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_triggerCount.setSmallDecimalPoint(False)
        self.lcdNumber_triggerCount.setDigitCount(6)
        self.lcdNumber_triggerCount.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_triggerCount.setProperty("value", 0.0)
        self.lcdNumber_triggerCount.setObjectName("lcdNumber_triggerCount")
        self.gridLayout_4.addWidget(self.lcdNumber_triggerCount, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.MeasurmentsDisplay, 0, QtCore.Qt.AlignTop)
        self.RbPIDSettings = QtWidgets.QGroupBox(self.LiveTab)
        self.RbPIDSettings.setObjectName("RbPIDSettings")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.RbPIDSettings)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_D = QtWidgets.QLabel(self.RbPIDSettings)
        self.label_D.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_D.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_D.setObjectName("label_D")
        self.gridLayout_6.addWidget(self.label_D, 3, 0, 1, 1)
        self.label_I = QtWidgets.QLabel(self.RbPIDSettings)
        self.label_I.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_I.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_I.setObjectName("label_I")
        self.gridLayout_6.addWidget(self.label_I, 2, 0, 1, 1)
        self.label_P = QtWidgets.QLabel(self.RbPIDSettings)
        self.label_P.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_P.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_P.setObjectName("label_P")
        self.gridLayout_6.addWidget(self.label_P, 1, 0, 1, 1)
        self.doubleSpinBox_P = QtWidgets.QDoubleSpinBox(self.RbPIDSettings)
        self.doubleSpinBox_P.setDecimals(8)
        self.doubleSpinBox_P.setMinimum(-1.0)
        self.doubleSpinBox_P.setMaximum(1.0)
        self.doubleSpinBox_P.setSingleStep(1e-06)
        self.doubleSpinBox_P.setProperty("value", -0.01)
        self.doubleSpinBox_P.setObjectName("doubleSpinBox_P")
        self.gridLayout_6.addWidget(self.doubleSpinBox_P, 1, 1, 1, 1)
        self.doubleSpinBox_D = QtWidgets.QDoubleSpinBox(self.RbPIDSettings)
        self.doubleSpinBox_D.setDecimals(8)
        self.doubleSpinBox_D.setMinimum(-99.0)
        self.doubleSpinBox_D.setObjectName("doubleSpinBox_D")
        self.gridLayout_6.addWidget(self.doubleSpinBox_D, 3, 1, 1, 1)
        self.doubleSpinBox_I = QtWidgets.QDoubleSpinBox(self.RbPIDSettings)
        self.doubleSpinBox_I.setDecimals(8)
        self.doubleSpinBox_I.setMinimum(-99.0)
        self.doubleSpinBox_I.setObjectName("doubleSpinBox_I")
        self.gridLayout_6.addWidget(self.doubleSpinBox_I, 2, 1, 1, 1)
        self.checkBox_PIDonoff = QtWidgets.QCheckBox(self.RbPIDSettings)
        self.checkBox_PIDonoff.setObjectName("checkBox_PIDonoff")
        self.gridLayout_6.addWidget(self.checkBox_PIDonoff, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.RbPIDSettings)
        self.FLICameraControl = QtWidgets.QGroupBox(self.LiveTab)
        self.FLICameraControl.setObjectName("FLICameraControl")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.FLICameraControl)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget_cameraControl = QtWidgets.QTabWidget(self.FLICameraControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_cameraControl.sizePolicy().hasHeightForWidth())
        self.tabWidget_cameraControl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.tabWidget_cameraControl.setFont(font)
        self.tabWidget_cameraControl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget_cameraControl.setAutoFillBackground(False)
        self.tabWidget_cameraControl.setObjectName("tabWidget_cameraControl")
        self.tab_Exposure = QtWidgets.QWidget()
        self.tab_Exposure.setObjectName("tab_Exposure")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_Exposure)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_CameraFilename = QtWidgets.QLabel(self.tab_Exposure)
        self.label_CameraFilename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_CameraFilename.setObjectName("label_CameraFilename")
        self.gridLayout_8.addWidget(self.label_CameraFilename, 10, 1, 1, 1)
        self.doubleSpinBox_ExposureTime = QtWidgets.QDoubleSpinBox(self.tab_Exposure)
        self.doubleSpinBox_ExposureTime.setObjectName("doubleSpinBox_ExposureTime")
        self.gridLayout_8.addWidget(self.doubleSpinBox_ExposureTime, 6, 3, 1, 1)
        self.label_ExposureTime = QtWidgets.QLabel(self.tab_Exposure)
        self.label_ExposureTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_ExposureTime.setObjectName("label_ExposureTime")
        self.gridLayout_8.addWidget(self.label_ExposureTime, 6, 1, 1, 1)
        self.radioButton_singleExposure = QtWidgets.QRadioButton(self.tab_Exposure)
        self.radioButton_singleExposure.setChecked(True)
        self.radioButton_singleExposure.setObjectName("radioButton_singleExposure")
        self.gridLayout_8.addWidget(self.radioButton_singleExposure, 2, 3, 1, 1)
        self.label_CameraStatus = QtWidgets.QLabel(self.tab_Exposure)
        self.label_CameraStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_CameraStatus.setObjectName("label_CameraStatus")
        self.gridLayout_8.addWidget(self.label_CameraStatus, 0, 1, 1, 1)
        self.pushButton_cameraStartExposure = QtWidgets.QPushButton(self.tab_Exposure)
        self.pushButton_cameraStartExposure.setEnabled(False)
        self.pushButton_cameraStartExposure.setObjectName("pushButton_cameraStartExposure")
        self.gridLayout_8.addWidget(self.pushButton_cameraStartExposure, 1, 1, 1, 1)
        self.pushButton_cameraStopExposure = QtWidgets.QPushButton(self.tab_Exposure)
        self.pushButton_cameraStopExposure.setEnabled(False)
        self.pushButton_cameraStopExposure.setObjectName("pushButton_cameraStopExposure")
        self.gridLayout_8.addWidget(self.pushButton_cameraStopExposure, 1, 3, 1, 1)
        self.lineEdit_cameraFilename = QtWidgets.QLineEdit(self.tab_Exposure)
        self.lineEdit_cameraFilename.setObjectName("lineEdit_cameraFilename")
        self.gridLayout_8.addWidget(self.lineEdit_cameraFilename, 10, 3, 1, 1)
        self.checkBox_saveCameraFile = QtWidgets.QCheckBox(self.tab_Exposure)
        self.checkBox_saveCameraFile.setObjectName("checkBox_saveCameraFile")
        self.gridLayout_8.addWidget(self.checkBox_saveCameraFile, 4, 3, 1, 1)
        self.radioButton_continuousExposures = QtWidgets.QRadioButton(self.tab_Exposure)
        self.radioButton_continuousExposures.setObjectName("radioButton_continuousExposures")
        self.gridLayout_8.addWidget(self.radioButton_continuousExposures, 2, 1, 1, 1)
        self.tabWidget_cameraControl.addTab(self.tab_Exposure, "")
        self.tab_CameraSetup = QtWidgets.QWidget()
        self.tab_CameraSetup.setObjectName("tab_CameraSetup")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_CameraSetup)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_CoolerToggle = QtWidgets.QPushButton(self.tab_CameraSetup)
        self.pushButton_CoolerToggle.setEnabled(False)
        self.pushButton_CoolerToggle.setCheckable(True)
        self.pushButton_CoolerToggle.setFlat(False)
        self.pushButton_CoolerToggle.setObjectName("pushButton_CoolerToggle")
        self.gridLayout_9.addWidget(self.pushButton_CoolerToggle, 1, 0, 1, 1)
        self.spinBox_CoolerSetPoint = QtWidgets.QSpinBox(self.tab_CameraSetup)
        self.spinBox_CoolerSetPoint.setMinimum(-40)
        self.spinBox_CoolerSetPoint.setMaximum(30)
        self.spinBox_CoolerSetPoint.setObjectName("spinBox_CoolerSetPoint")
        self.gridLayout_9.addWidget(self.spinBox_CoolerSetPoint, 1, 1, 1, 1)
        self.pushButton_connectCamera = QtWidgets.QPushButton(self.tab_CameraSetup)
        self.pushButton_connectCamera.setObjectName("pushButton_connectCamera")
        self.gridLayout_9.addWidget(self.pushButton_connectCamera, 0, 0, 1, 1)
        self.pushButton_DisconnectCamera = QtWidgets.QPushButton(self.tab_CameraSetup)
        self.pushButton_DisconnectCamera.setEnabled(False)
        self.pushButton_DisconnectCamera.setObjectName("pushButton_DisconnectCamera")
        self.gridLayout_9.addWidget(self.pushButton_DisconnectCamera, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 2, 1, 1, 1)
        self.tabWidget_cameraControl.addTab(self.tab_CameraSetup, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_cameraControl, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.FLICameraControl)
        spacerItem2 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.tabWidget_controls.addTab(self.LiveTab, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabWidgetPage2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabWidgetPage2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_localIP = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_localIP.setReadOnly(True)
        self.lineEdit_localIP.setObjectName("lineEdit_localIP")
        self.gridLayout_7.addWidget(self.lineEdit_localIP, 0, 1, 1, 1)
        self.lineEdit_rpIP = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_rpIP.setReadOnly(True)
        self.lineEdit_rpIP.setObjectName("lineEdit_rpIP")
        self.gridLayout_7.addWidget(self.lineEdit_rpIP, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 1, 1, 1, QtCore.Qt.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 2, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabWidgetPage2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_11.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.tabWidget_controls.addTab(self.tabWidgetPage2, "")
        self.horizontalLayout.addWidget(self.tabWidget_controls, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        RbMoniter.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RbMoniter)
        self.statusbar.setObjectName("statusbar")
        RbMoniter.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(RbMoniter)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(RbMoniter)
        self.tabWidget_display.setCurrentIndex(2)
        self.tabWidget_controls.setCurrentIndex(0)
        self.tabWidget_cameraControl.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(RbMoniter)

    def retranslateUi(self, RbMoniter):
        _translate = QtCore.QCoreApplication.translate
        RbMoniter.setWindowTitle(_translate("RbMoniter", "SAIL Photonic Comb Rb Lock/Moniter"))
        self.tabWidget_display.setTabText(self.tabWidget_display.indexOf(self.tab_fullRBLockMoniter), _translate("RbMoniter", "Full Moniter"))
        self.tabWidget_display.setTabText(self.tabWidget_display.indexOf(self.tab_RBLockDiagnostic), _translate("RbMoniter", "Diagnostic"))
        self.label_fullCCDImage.setText(_translate("RbMoniter", "Full Image"))
        self.label_MaxZoom.setText(_translate("RbMoniter", "Max Value Zoom"))
        self.label_mouseZoom.setText(_translate("RbMoniter", "Mouse Zoom"))
        self.tabWidget_display.setTabText(self.tabWidget_display.indexOf(self.tab_SpecCamera), _translate("RbMoniter", "FLI VIewer"))
        self.tabWidget_display.setTabText(self.tabWidget_display.indexOf(self.tab_log), _translate("RbMoniter", "Log"))
        self.RbLockDataAqusitionControls.setTitle(_translate("RbMoniter", "Data Aquisition"))
        self.label_TempSetPoint.setText(_translate("RbMoniter", "Temp Set Point"))
        self.pushButton_clearData.setText(_translate("RbMoniter", "Clear Data"))
        self.label_RbSmoothWindow.setText(_translate("RbMoniter", "Rb Smooth Window"))
        self.checkBox_etalonsmoothing.setText(_translate("RbMoniter", "Smooth Etalon"))
        self.doubleSpinBox_tempsetpoint.setSuffix(_translate("RbMoniter", "°C"))
        self.label_DisplayUpdateRate.setText(_translate("RbMoniter", "Update Rate (sam)"))
        self.pushButton_savedata.setText(_translate("RbMoniter", "Save Date"))
        self.label_EtalonBinSize.setText(_translate("RbMoniter", "Etalon Bin Size"))
        self.label_plotwindowsize.setText(_translate("RbMoniter", "Plot Window Size"))
        self.checkBox_fitting.setText(_translate("RbMoniter", "Fitting Enabled"))
        self.startbutton.setText(_translate("RbMoniter", "Start"))
        self.doubleSpinBox_etalonbinsize.setSuffix(_translate("RbMoniter", " sec"))
        self.stopbutton.setText(_translate("RbMoniter", "Stop"))
        self.MeasurmentsDisplay.setTitle(_translate("RbMoniter", "Measurements"))
        self.label_dateRate.setText(_translate("RbMoniter", "<html><head/><body><p align=\"right\">Data Rate</p></body></html>"))
        self.label_StdEtalon.setText(_translate("RbMoniter", "Std Etalon"))
        self.label_TriggerCount.setText(_translate("RbMoniter", "<html><head/><body><p align=\"right\">Trigger Cnt</p></body></html>"))
        self.label_StdRb.setText(_translate("RbMoniter", "<html><head/><body><p align=\"right\">Std Rb</p></body></html>"))
        self.label_Fitrate.setText(_translate("RbMoniter", "<html><head/><body><p align=\"right\">Fit rate</p></body></html>"))
        self.RbPIDSettings.setTitle(_translate("RbMoniter", "PID"))
        self.label_D.setText(_translate("RbMoniter", "D"))
        self.label_I.setText(_translate("RbMoniter", "I"))
        self.label_P.setText(_translate("RbMoniter", "P"))
        self.checkBox_PIDonoff.setText(_translate("RbMoniter", "Enabled"))
        self.FLICameraControl.setTitle(_translate("RbMoniter", "FLI CCD Control"))
        self.label_CameraFilename.setText(_translate("RbMoniter", "Filename"))
        self.label_ExposureTime.setText(_translate("RbMoniter", "Seconds"))
        self.radioButton_singleExposure.setText(_translate("RbMoniter", "Single"))
        self.label_CameraStatus.setText(_translate("RbMoniter", "Camera Status:"))
        self.pushButton_cameraStartExposure.setText(_translate("RbMoniter", "Start"))
        self.pushButton_cameraStopExposure.setText(_translate("RbMoniter", "Stop"))
        self.checkBox_saveCameraFile.setText(_translate("RbMoniter", "Save File"))
        self.radioButton_continuousExposures.setText(_translate("RbMoniter", "NonStop"))
        self.tabWidget_cameraControl.setTabText(self.tabWidget_cameraControl.indexOf(self.tab_Exposure), _translate("RbMoniter", "Exposure"))
        self.pushButton_CoolerToggle.setText(_translate("RbMoniter", "Cooler"))
        self.pushButton_connectCamera.setText(_translate("RbMoniter", "Connect"))
        self.pushButton_DisconnectCamera.setText(_translate("RbMoniter", "Disconnect"))
        self.tabWidget_cameraControl.setTabText(self.tabWidget_cameraControl.indexOf(self.tab_CameraSetup), _translate("RbMoniter", "Setup"))
        self.tabWidget_controls.setTabText(self.tabWidget_controls.indexOf(self.LiveTab), _translate("RbMoniter", "Live"))
        self.groupBox_3.setTitle(_translate("RbMoniter", "Receiver Settings"))
        self.label_13.setText(_translate("RbMoniter", "Local IP"))
        self.label_14.setText(_translate("RbMoniter", "RP IP"))
        self.groupBox_5.setTitle(_translate("RbMoniter", "FLI"))
        self.label_22.setText(_translate("RbMoniter", "Address"))
        self.lineEdit_2.setText(_translate("RbMoniter", "/dev/fliusb0"))
        self.tabWidget_controls.setTabText(self.tabWidget_controls.indexOf(self.tabWidgetPage2), _translate("RbMoniter", "Settings"))
        self.actionAbout.setText(_translate("RbMoniter", "About"))

from pyqtgraph import GraphicsLayoutWidget, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RbMoniter = QtWidgets.QMainWindow()
    ui = Ui_RbMoniter()
    ui.setupUi(RbMoniter)
    RbMoniter.show()
    sys.exit(app.exec_())

